# Inserts list of contributors and community members into ./docs/credits.md
name: 📊 Generate Contributor Credits
on:
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '0 5 * * 6' # Every Saturday morning.
jobs:
  # Job #1 - Inserts sponsors into README
  insert-sponsors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Generate Sponsors in Credits 💖
        uses: JamesIves/github-sponsors-readme-action@v1.4.0
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          file: '.github/README.md'
  # Job #2 - Inserts contributors into README
  insert-credits:
    runs-on: ubuntu-latest
    name: Inserts contributors into credits.md
    steps:
    - name: Contribute List - Credits Page
      uses: akhilmhdh/contributors-readme-action@v2.3
      env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
      with:
        image_size: 80
        readme_path: .github/README.md
        columns_per_row: 6
        commit_message: 'Updates contributors list'
        committer_username: liss-bot
        committer_email: liss-bot@d0h.co
